### ISSUE TITLE
Problem when loading the ldap module inside Eclipse

### ISSUE THREAD

**Issue by debbabi** [cristal-ise/lookup-ldap#4]
When launching a Cristal-Dev inside Eclipse, I have the following exception.
It can not loads the "ldap" module because the `ResourceUrl` of ldap module points to a non existing folder. That is, maven does not create `target/classes/org/cristalise/lookup/ldap/resources/` because the `src/main/ressources` has only the excluded file "module.xml". 

```
2015-08-06 12:49:54.953 (1.179s) - ERROR  : URL org/cristalise/lookup/ldap/resources/ could not be found
2015-08-06 12:49:54.955 (1.181s) - EXCEPTION:org.cristalise.kernel.common.InvalidDataException: IDL:org.cristalise.kernel/common/InvalidDataException:1.0
    at org.cristalise.kernel.process.resource.Resource.getURLorResURL(Resource.java:129)
    at org.cristalise.kernel.process.resource.Resource.addModuleBaseURL(Resource.java:94)
    at org.cristalise.kernel.process.module.ModuleManager.<init>(ModuleManager.java:73)
    at org.cristalise.kernel.process.Gateway.init(Gateway.java:138)
    at org.cristalise.kernel.process.Gateway.init(Gateway.java:102)
    at org.cristalise.kernel.process.StandardServer.standardInitialisation(StandardServer.java:47)
    at org.cristalise.kernel.process.StandardServer.main(StandardServer.java:65)

2015-08-06 12:49:54.955 (1.181s) - EXCEPTION:org.cristalise.kernel.process.module.ModuleException: Could not load module.xml from file:/Users/debbabi/OneDrive/Workspaces_Git/CRISTAL-ISE/lookup-ldap/target/classes/META-INF/cristal/module.xml
    at org.cristalise.kernel.process.module.ModuleManager.<init>(ModuleManager.java:85)
    at org.cristalise.kernel.process.Gateway.init(Gateway.java:138)
    at org.cristalise.kernel.process.Gateway.init(Gateway.java:102)
    at org.cristalise.kernel.process.StandardServer.standardInitialisation(StandardServer.java:47)
    at org.cristalise.kernel.process.StandardServer.main(StandardServer.java:65)

Exception in thread "main" org.cristalise.kernel.common.InvalidDataException: IDL:org.cristalise.kernel/common/InvalidDataException:1.0  Could not load module definitions.
    at org.cristalise.kernel.process.Gateway.init(Gateway.java:141)
    at org.cristalise.kernel.process.Gateway.init(Gateway.java:102)
    at org.cristalise.kernel.process.StandardServer.standardInitialisation(StandardServer.java:47)
    at org.cristalise.kernel.process.StandardServer.main(StandardServer.java:65)
```

**Comment by abranson** [comment]
I've removed that unnecessary ResourceURL, but that's not causing this exception. The URL not being found should not be a fatal exception, and the module.xml should still be found in the META-INF. 

Does the file file:/Users/debbabi/OneDrive/Workspaces_Git/CRISTAL-ISE/lookup-ldap/target/classes/META-INF/cristal/module.xml exist?

**Comment by abranson** [comment]
Did you solve this?

**Comment by debbabi** [comment]
Yes it is resolved now.
